[build-system]
requires = ["setuptools", "wheel"]

[project]
authors = [
    {name = "Kevin Exton", email = "kcexton01@gmail.com"}
]
dependencies = ["numpy>=1.24.3"]
description = "Cluster Simulation"
name = "simulation"
requires-python = ">=3.11"
version = "0.1"
